namespace predictor
{
	public static class Location
	{
		public static double ToDistance(string location)
		{
			switch (location)
			{
				case "29. Novembra":									return 1.4	  ;
				case "Ada Ciganlija":									return 6.8	  ;
				case "Altina":											return 13.7	  ;
				case "Andrićev venac":									return 0.9	  ;
				case "Autokomanda":										return 3.8	  ;
				case "Avala":											return 5.0	  ;
				case "Bajlonijeva pijaca":								return 0.65	  ;
				case "Banjica":											return 6.7	  ;
				case "Banovo brdo":										return 7.3	  ;
				case "Barajevo":										return 33.9	  ;
				case "Batajnica":										return 22.9	  ;
				case "Bele vode":										return 11.6	  ;
				case "Beli potok":										return 19.0	  ;
				case "Belvil":											return 6.2	  ;
				case "Beograd na vodi":									return 2.7	  ;
				case "Beograđanka ( centar )":							return 1.1	  ;
				case "Bežanija":										return 8.3	  ;
				case "Bežanijska kosa I":								return 8.2	  ;
				case "Bežanijska kosa II":								return 8.6	  ;
				case "Bežanijska kosa III":								return 8.1	  ;
				case "Bogoslovija":										return 2.9	  ;
				case "Borča I":											return 10.5	  ;
				case "Borča II":										return 10.8	  ;
				case "Borča III":										return 11.6	  ;
				case "Borča IV":										return 11.3	  ;
				case "Borča V":											return 11.3	  ;
				case "Botanička bašta":									return 1.3	  ;
				case "Braće Jerković":									return 6.6	  ;
				case "Bulbuder":										return 3.8	  ;
				case "Bulevar Kr. Aleksandra":							return 5.6	  ;
				case "Centar (uži)":									return 0	  ;
				case "Cerak":											return 10.7	  ;
				case "Cerak vinogradi":									return 12.5	  ;
				case "Crveni krst":										return 3.7	  ;
				case "Čubura":											return 3.0	  ;
				case "Čukarica":										return 6.9	  ;
				case "Čukarička padina":								return 7.3	  ;
				case "Cvetanova ćuprija":								return 9.9	  ;
				case "Cvetkova pijaca":									return 4.6	  ;
				case "Cvetni trg":										return 1.3	  ;
				case "Cvijićeva":										return 1.9	  ;
				case "Dedinje (25. maj)":								return 5.7	  ;
				case "Dedinje (Beli dvor)":								return 6.2	  ;
				case "Dedinje (RTV Pink)":								return 5.4	  ;
				case "Denkova bašta":									return 5.3	  ;
				case "Đeram pijaca":									return 3.2	  ;
				case "Dobanovci":										return 23.6	  ;
				case "Donji Dorćol":									return 1.5	  ;
				case "Dunavski kej":									return 2.0	  ;
				case "Dušanovac":										return 5.5	  ;
				case "Farmaceutski fakultet":							return 8.9	  ;
				case "Filmski grad":									return 11.2	  ;
				case "Galenika":										return 13.5	  ;
				case "Glumčevo brdo":									return 29.1	  ;
				case "Golf naselje":									return 8.7	  ;
				case "Gornji Dorćol":									return 1.5	  ;
				case "Gradska bolnica":									return 4.2	  ;
				case "Grocka":											return 29.1	  ;
				case "Gundulićev venac":								return 0.9	  ;
				case "Hadžipopovac":									return 2.8	  ;
				case "Hala Pionir":										return 2.4	  ;
				case "Ibarska magistrala":								return 14.4	  ;
				case "Institut za majku i dete":						return 8.2	  ;
				case "Jajinci":											return 9.4	  ;
				case "Julino brdo":										return 9.6	  ;
				case "Južni bulevar":									return 3.4	  ;
				case "Kalemegdan":										return 2.1	  ;
				case "Kalenić pijaca":									return 2.7	  ;
				case "Kaluđerica":										return 13.3	  ;
				case "Kanarevo brdo":									return 8.1	  ;
				case "Karaburma":										return 4.1	  ;
				case "Klinički centar":									return 2.2	  ;
				case "Kluz":											return 9.0	  ;
				case "Knez Mihajlova ( centar )":						return 0	  ;
				case "Kneza Miloša ( centar )":							return 1.0	  ;
				case "Kneževac":										return 12.2	  ;
				case "Konjarnik":										return 6.3	  ;
				case "Kopitareva gradina":								return 0.9	  ;
				case "Kosančićev venac":								return 1.1	  ;
				case "Košutnjak":										return 10.1	  ;
				case "Kotež":											return 7.6	  ;
				case "Krnjača":											return 6.8	  ;
				case "Kumodraž I":										return 10.5	  ;
				case "Kumodraž II":										return 8.7	  ;
				case "Labudovo brdo":									return 13.4	  ;
				case "Ledine":											return 11.4	  ;
				case "Lekino brdo":										return 4.5	  ;
				case "Leštane":											return 17.8	  ;
				case "Lion":											return 3.7	  ;
				case "Lipov lad":										return 4.0	  ;
				case "Lipovačka šuma":									return 26.0	  ;
				case "Lisičji jarak":									return 16.6	  ;
				case "Lisičji potok":									return 7.2	  ;
				case "Makiš":											return 11.7	  ;
				case "Mali mokri lug":									return 7.9	  ;
				case "Manjež":											return 1.3	  ;
				case "Marinkova bara":									return 7.6	  ;
				case "Medak padina":									return 8.6	  ;
				case "Medaković I":										return 7.4	  ;
				case "Medaković II":									return 6.9	  ;
				case "Medaković III":									return 6.9	  ;
				case "Miljakovac I":									return 9.4	  ;
				case "Miljakovac II":									return 9.2	  ;
				case "Miljakovac III":									return 9.7	  ;
				case "Mirijevo I":										return 8.5	  ;
				case "Mirijevo II":										return 7.4	  ;
				case "Mirijevo III":									return 8.1	  ;
				case "Mirijevo IV":										return 8.7	  ;
				case "Neimar":											return 2.9	  ;
				case "Novi Beograd":									return 8.2	  ;
				case "Novi Beograd Blok 1 (Fontana)":					return 5.0	  ;
				case "Novi Beograd Blok 10":							return 4.7	  ;
				case "Novi Beograd Blok 11 (Hotel Jugoslavija)":		return 4.7	  ;
				case "Novi Beograd Blok 11a (Opština NBG)":				return 4.9	  ;
				case "Novi Beograd Blok 11b":							return 5.0	  ;
				case "Novi Beograd Blok 11c (Stari Merkator)":			return 5.2	  ;
				case "Novi Beograd Blok 12 (YUBC)":						return 4.6	  ;
				case "Novi Beograd Blok 19 (Sava Centar)":				return 4.0	  ;
				case "Novi Beograd Blok 19a":							return 4.3	  ;
				case "Novi Beograd Blok 2":								return 5.2	  ;
				case "Novi Beograd Blok 20 (Hotel Hayat)":				return 3.3	  ;
				case "Novi Beograd Blok 21 (10. Gimnazija)":			return 2.9	  ;
				case "Novi Beograd Blok 22":							return 3.4	  ;
				case "Novi Beograd Blok 23":							return 4.0	  ;
				case "Novi Beograd Blok 24 (Super Vero)":				return 4.7	  ;
				case "Novi Beograd Blok 25 (Arena)":					return 4.1	  ;
				case "Novi Beograd Blok 28 (Potkovica)":				return 5.4	  ;
				case "Novi Beograd Blok 29":							return 4.4	  ;
				case "Novi Beograd Blok 3":								return 5.7	  ;
				case "Novi Beograd Blok 30 (B92)":						return 4.2	  ;
				case "Novi Beograd Blok 31 (Merkator)":					return 4.5	  ;
				case "Novi Beograd Blok 33 (Genex kula)":				return 5.2	  ;
				case "Novi Beograd Blok 34 (Studentski grad)":			return 5.9	  ;
				case "Novi Beograd Blok 37":							return 7.3	  ;
				case "Novi Beograd Blok 38 (OŠ Ratko Mitrović)":		return 6.1	  ;
				case "Novi Beograd Blok 4 (Politehnička akademija)":	return 5.9	  ;
				case "Novi Beograd Blok 44 (Piramida)":					return 7.8	  ;
				case "Novi Beograd Blok 45 (TC Enjub)":					return 8.5	  ;
				case "Novi Beograd Blok 49":							return 8.2	  ;
				case "Novi Beograd Blok 5":								return 5.6	  ;
				case "Novi Beograd Blok 61":							return 9.0	  ;
				case "Novi Beograd Blok 62":							return 8.4	  ;
				case "Novi Beograd Blok 63":							return 8.5	  ;
				case "Novi Beograd Blok 64":							return 7.1	  ;
				case "Novi Beograd Blok 65":							return 6.5	  ;
				case "Novi Beograd Blok 66 (Tramvajska štala)":			return 6.6	  ;
				case "Novi Beograd Blok 67":							return 6.2	  ;
				case "Novi Beograd Blok 67a":							return 6.2	  ;
				case "Novi Beograd Blok 7 (Paviljoni)":					return 6.1	  ;
				case "Novi Beograd Blok 70 (Kineski TC)":				return 7.0	  ;
				case "Novi Beograd Blok 70a":							return 6.3	  ;
				case "Novi Beograd Blok 71":							return 9.1	  ;
				case "Novi Beograd Blok 72":							return 8.9	  ;
				case "Novi Beograd Blok 8a":							return 5.9	  ;
				case "Novi Beograd Blok 8a (Paviljoni)":				return 5.9	  ;
				case "Novi Beograd Blok 9":								return 5.8	  ;
				case "Novi Beograd Blok 9a (Dom Zdravlja)":				return 5.2	  ;
				case "Novo groblje":									return 2.7	  ;
				case "Obilićev venac":									return 1.0	  ;
				case "Olimp":											return 5.0	  ;
				case "Ostružnica":										return 19.2	  ;
				case "Ovča":											return 13.0	  ;
				case "Padinska skela":									return 24.4	  ;
				case "Palata pravde":									return 2.0	  ;
				case "Palilula":										return 1.3	  ;
				case "Palilulska pijaca":								return 1.0	  ;
				case "Partizanov stadion":								return 4.2	  ;
				case "Pašino brdo":										return 4.6	  ;
				case "Petlovo brdo":									return 13.3	  ;
				case "Plavi Horizonti":									return 13.6	  ;
				case "Politika ( centar )":								return 0.35	  ;
				case "Poštanska štedionica":							return 8.4	  ;
				case "Pregrevica":										return 8.5	  ;
				case "Profesorska kolonija":							return 1.8	  ;
				case "Radiofar":										return 16.2	  ;
				case "Rakovica":										return 10.7	  ;
				case "Resnik":											return 15.2	  ;
				case "Retenzija":										return 5.7	  ;
				case "Rospi ćuprija":									return 5.3	  ;
				case "Rušanj":											return 20.2	  ;
				case "Sarajevska":										return 2.0	  ;
				case "Sava mala":										return 1.0	  ;
				case "Savski trg":										return 1.6	  ;
				case "Savski venac":									return 4.8	  ;
				case "Senjak":											return 4.7	  ;
				case "Severni bulevar":									return 3.2	  ;
				case "Skadarlija":										return 0.4	  ;
				case "Skojevsko naselje":								return 11.0	  ;
				case "Slavija":											return 1.7	  ;
				case "Slavujev venac":									return 3.0	  ;
				case "Sopot":											return 43.0	  ;
				case "Sremčica":										return 21.5	  ;
				case "Stari Grad":										return 0.35	  ;
				case "Studentski Trg ( centar )":						return 1.0	  ;
				case "Šumice":											return 5.2	  ;
				case "Sunčana padina":									return 8.5	  ;
				case "Surčin":											return 18.2	  ;
				case "Tašmajdan":										return 1.0	  ;
				case "Tehnicki fakulteti":								return 2.1	  ;
				case "Terazije ( centar )":								return 0.5	  ;
				case "Topčider":										return 5.3	  ;
				case "Topličin venac":									return 1.0	  ;
				case "Tošin bunar":										return 6.8	  ;
				case "Trg Republike ( centar )":						return 0	  ;
				case "Trošarina":										return 6.8	  ;
				case "Učiteljsko naselje":								return 5.9	  ;
				case "Veliki mokri lug":								return 10.4	  ;
				case "Veljko Vlahović":									return 18.6	  ;
				case "Vidikovac":										return 12.2	  ;
				case "Vidikovačka padina":								return 12.2	  ;
				case "Viline vode":										return 2.3	  ;
				case "Vinča":											return 14.7	  ;
				case "Višnjica":										return 7.9	  ;
				case "Višnjička banja":									return 6.2	  ;
				case "Vojvode Vlahovića":								return 9.0	  ;
				case "Voždovac":										return 5.0	  ;
				case "Vračar (Centar)":									return 2.7	  ;
				case "Vračar (Hram)":									return 2.3	  ;
				case "Vukov spomenik":									return 2.8	  ;
				case "Žarkovo":											return 9.3	  ;
				case "Zeleni venac":									return 0.85	  ;
				case "Zeleno Brdo":										return 5.9	  ;
				case "Železnik":										return 16.3	  ;
				case "Zemun (Bačka)":									return 12.7	  ;
				case "Zemun (Cara Dušana)":								return 8.5	  ;
				case "Zemun (Centar)":									return 23.0	  ;
				case "Zemun (Ćukovac)":									return 7.4	  ;
				case "Zemun (Gardoš)":									return 7.4	  ;
				case "Zemun (Gornji grad)":								return 9.6	  ;
				case "Zemun (Kalvarija)":								return 8.1	  ;
				case "Zemun (Kej)":										return 6.3	  ;
				case "Zemun (Marije Bursać)":							return 8.7	  ;
				case "Zemun (Meandri)":									return 8.7	  ;
				case "Zemun (Nova Galenika)":							return 13.5	  ;
				case "Zemun (Novi Grad)":								return 10.9	  ;
				case "Zemun (Save Kovačevića)":							return 8.2	  ;
				case "Zemun (Teleoptik)":								return 8.5	  ;
				case "Zemun Polje":										return 16.5	  ;
				case "Zira":											return 2.5	  ;
				case "Zvezdara":										return 3.9	  ;
				case "Zvezdarska Šuma":									return 5.4	  ;
				case "Zvezdin stadion":									return 4.2	  ;
			}

			return 0;
		}
	}
}
