namespace predictor
{
	public static class Location
	{
		public static double ToDistance(string location)
		{
			switch (location)
			{
				case "29. Novembra":									return 1;
				case "Ada Ciganlija":									return 2;
				case "Altina":											return 3;
				case "Andrićev venac":									return 4;
				case "Autokomanda":										return 5;
				case "Avala":											return 6;
				case "Bajlonijeva pijaca":								return 7;
				case "Banjica":											return 8;
				case "Banovo brdo":										return 9;
				case "Barajevo":										return 10;
				case "Batajnica":										return 11;
				case "Bele vode":										return 12;
				case "Beli potok":										return 13;
				case "Belvil":											return 14;
				case "Beograd na vodi":									return 15;
				case "Beograđanka ( centar )":							return 16;
				case "Bežanija":										return 17;
				case "Bežanijska kosa I":								return 18;
				case "Bežanijska kosa II":								return 19;
				case "Bežanijska kosa III":								return 20;
				case "Bogoslovija":										return 21;
				case "Borča I":											return 22;
				case "Borča II":										return 23;
				case "Borča III":										return 24;
				case "Borča IV":										return 25;
				case "Borča V":											return 26;
				case "Botanička bašta":									return 27;
				case "Braće Jerković":									return 28;
				case "Bulbuder":										return 29;
				case "Bulevar Kr. Aleksandra":							return 30;
				case "Centar (uži)":									return 31;
				case "Cerak":											return 32;
				case "Cerak vinogradi":									return 33;
				case "Crveni krst":										return 34;
				case "Čubura":											return 35;
				case "Čukarica":										return 36;
				case "Čukarička padina":								return 37;
				case "Cvetanova ćuprija":								return 38;
				case "Cvetkova pijaca":									return 39;
				case "Cvetni trg":										return 40;
				case "Cvijićeva":										return 41;
				case "Dedinje (25. maj)":								return 42;
				case "Dedinje (Beli dvor)":								return 43;
				case "Dedinje (RTV Pink)":								return 44;
				case "Denkova bašta":									return 45;
				case "Đeram pijaca":									return 46;
				case "Dobanovci":										return 47;
				case "Donji Dorćol":									return 48;
				case "Dunavski kej":									return 49;
				case "Dušanovac":										return 50;
				case "Farmaceutski fakultet":							return 51;
				case "Filmski grad":									return 52;
				case "Galenika":										return 53;
				case "Glumčevo brdo":									return 54;
				case "Golf naselje":									return 55;
				case "Gornji Dorćol":									return 56;
				case "Gradska bolnica":									return 57;
				case "Grocka":											return 58;
				case "Gundulićev venac":								return 59;
				case "Hadžipopovac":									return 60;
				case "Hala Pionir":										return 61;
				case "Ibarska magistrala":								return 62;
				case "Institut za majku i dete":						return 63;
				case "Jajinci":											return 64;
				case "Julino brdo":										return 65;
				case "Južni bulevar":									return 66;
				case "Kalemegdan":										return 67;
				case "Kalenić pijaca":									return 68;
				case "Kaluđerica":										return 69;
				case "Kanarevo brdo":									return 70;
				case "Karaburma":										return 71;
				case "Klinički centar":									return 72;
				case "Kluz":											return 73;
				case "Knez Mihajlova ( centar )":						return 74;
				case "Kneza Miloša ( centar )":							return 75;
				case "Kneževac":										return 76;
				case "Konjarnik":										return 77;
				case "Kopitareva gradina":								return 78;
				case "Kosančićev venac":								return 79;
				case "Košutnjak":										return 80;
				case "Kotež":											return 81;
				case "Krnjača":											return 82;
				case "Kumodraž I":										return 83;
				case "Kumodraž II":										return 84;
				case "Labudovo brdo":									return 85;
				case "Ledine":											return 86;
				case "Lekino brdo":										return 87;
				case "Leštane":											return 88;
				case "Lion":											return 89;
				case "Lipov lad":										return 90;
				case "Lipovačka šuma":									return 91;
				case "Lisičji jarak":									return 92;
				case "Lisičji potok":									return 93;
				case "Makiš":											return 94;
				case "Mali mokri lug":									return 95;
				case "Manjež":											return 96;
				case "Marinkova bara":									return 97;
				case "Medak padina":									return 98;
				case "Medaković I":										return 99;
				case "Medaković II":									return 100;
				case "Medaković III":									return 101;
				case "Miljakovac I":									return 102;
				case "Miljakovac II":									return 103;
				case "Miljakovac III":									return 104;
				case "Mirijevo I":										return 105;
				case "Mirijevo II":										return 106;
				case "Mirijevo III":									return 107;
				case "Mirijevo IV":										return 108;
				case "Neimar":											return 109;
				case "Novi Beograd":									return 110;
				case "Novi Beograd Blok 1 (Fontana)":					return 111;
				case "Novi Beograd Blok 10":							return 112;
				case "Novi Beograd Blok 11 (Hotel Jugoslavija)":		return 113;
				case "Novi Beograd Blok 11a (Opština NBG)":				return 114;
				case "Novi Beograd Blok 11b":							return 115;
				case "Novi Beograd Blok 11c (Stari Merkator)":			return 116;
				case "Novi Beograd Blok 12 (YUBC)":						return 117;
				case "Novi Beograd Blok 19 (Sava Centar)":				return 118;
				case "Novi Beograd Blok 19a":							return 119;
				case "Novi Beograd Blok 2":								return 120;
				case "Novi Beograd Blok 20 (Hotel Hayat)":				return 121;
				case "Novi Beograd Blok 21 (10. Gimnazija)":			return 122;
				case "Novi Beograd Blok 22":							return 123;
				case "Novi Beograd Blok 23":							return 124;
				case "Novi Beograd Blok 24 (Super Vero)":				return 125;
				case "Novi Beograd Blok 25 (Arena)":					return 126;
				case "Novi Beograd Blok 28 (Potkovica)":				return 127;
				case "Novi Beograd Blok 29":							return 128;
				case "Novi Beograd Blok 3":								return 129;
				case "Novi Beograd Blok 30 (B92)":						return 130;
				case "Novi Beograd Blok 31 (Merkator)":					return 131;
				case "Novi Beograd Blok 33 (Genex kula)":				return 132;
				case "Novi Beograd Blok 34 (Studentski grad)":			return 133;
				case "Novi Beograd Blok 37":							return 134;
				case "Novi Beograd Blok 38 (OŠ Ratko Mitrović)":		return 135;
				case "Novi Beograd Blok 4 (Politehnička akademija)":	return 136;
				case "Novi Beograd Blok 44 (Piramida)":					return 137;
				case "Novi Beograd Blok 45 (TC Enjub)":					return 138;
				case "Novi Beograd Blok 49":							return 139;
				case "Novi Beograd Blok 5":								return 140;
				case "Novi Beograd Blok 61":							return 141;
				case "Novi Beograd Blok 62":							return 142;
				case "Novi Beograd Blok 63":							return 143;
				case "Novi Beograd Blok 64":							return 144;
				case "Novi Beograd Blok 65":							return 145;
				case "Novi Beograd Blok 66 (Tramvajska štala)":			return 146;
				case "Novi Beograd Blok 67":							return 147;
				case "Novi Beograd Blok 67a":							return 148;
				case "Novi Beograd Blok 7 (Paviljoni)":					return 149;
				case "Novi Beograd Blok 70 (Kineski TC)":				return 150;
				case "Novi Beograd Blok 70a":							return 151;
				case "Novi Beograd Blok 71":							return 152;
				case "Novi Beograd Blok 72":							return 153;
				case "Novi Beograd Blok 8a":							return 154;
				case "Novi Beograd Blok 8a (Paviljoni)":				return 155;
				case "Novi Beograd Blok 9":								return 156;
				case "Novi Beograd Blok 9a (Dom Zdravlja)":				return 157;
				case "Novo groblje":									return 158;
				case "Obilićev venac":									return 159;
				case "Olimp":											return 160;
				case "Ostružnica":										return 161;
				case "Ovča":											return 162;
				case "Padinska skela":									return 163;
				case "Palata pravde":									return 164;
				case "Palilula":										return 165;
				case "Palilulska pijaca":								return 166;
				case "Partizanov stadion":								return 167;
				case "Pašino brdo":										return 168;
				case "Petlovo brdo":									return 169;
				case "Plavi Horizonti":									return 170;
				case "Politika ( centar )":								return 171;
				case "Poštanska štedionica":							return 172;
				case "Pregrevica":										return 173;
				case "Profesorska kolonija":							return 174;
				case "Radiofar":										return 175;
				case "Rakovica":										return 176;
				case "Resnik":											return 177;
				case "Retenzija":										return 178;
				case "Rospi ćuprija":									return 179;
				case "Rušanj":											return 180;
				case "Sarajevska":										return 181;
				case "Sava mala":										return 182;
				case "Savski trg":										return 183;
				case "Savski venac":									return 184;
				case "Senjak":											return 185;
				case "Severni bulevar":									return 186;
				case "Skadarlija":										return 187;
				case "Skojevsko naselje":								return 188;
				case "Slavija":											return 189;
				case "Slavujev venac":									return 190;
				case "Sopot":											return 191;
				case "Sremčica":										return 192;
				case "Stari Grad":										return 193;
				case "Studentski Trg ( centar )":						return 194;
				case "Šumice":											return 195;
				case "Sunčana padina":									return 196;
				case "Surčin":											return 197;
				case "Tašmajdan":										return 198;
				case "Tehnicki fakulteti":								return 199;
				case "Terazije ( centar )":								return 200;
				case "Topčider":										return 201;
				case "Topličin venac":									return 202;
				case "Tošin bunar":										return 203;
				case "Trg Republike ( centar )":						return 204;
				case "Trošarina":										return 205;
				case "Učiteljsko naselje":								return 206;
				case "Veliki mokri lug":								return 207;
				case "Veljko Vlahović":									return 208;
				case "Vidikovac":										return 209;
				case "Vidikovačka padina":								return 210;
				case "Viline vode":										return 211;
				case "Vinča":											return 212;
				case "Višnjica":										return 213;
				case "Višnjička banja":									return 214;
				case "Vojvode Vlahovića":								return 215;
				case "Voždovac":										return 216;
				case "Vračar (Centar)":									return 217;
				case "Vračar (Hram)":									return 218;
				case "Vukov spomenik":									return 219;
				case "Žarkovo":											return 220;
				case "Zeleni venac":									return 221;
				case "Zeleno Brdo":										return 222;
				case "Železnik":										return 223;
				case "Zemun (Bačka)":									return 224;
				case "Zemun (Cara Dušana)":								return 225;
				case "Zemun (Centar)":									return 226;
				case "Zemun (Ćukovac)":									return 227;
				case "Zemun (Gardoš)":									return 228;
				case "Zemun (Gornji grad)":								return 229;
				case "Zemun (Kalvarija)":								return 230;
				case "Zemun (Kej)":										return 231;
				case "Zemun (Marije Bursać)":							return 232;
				case "Zemun (Meandri)":									return 233;
				case "Zemun (Nova Galenika)":							return 234;
				case "Zemun (Novi Grad)":								return 235;
				case "Zemun (Save Kovačevića)":							return 236;
				case "Zemun (Teleoptik)":								return 237;
				case "Zemun Polje":										return 238;
				case "Zira":											return 239;
				case "Zvezdara":										return 240;
				case "Zvezdarska Šuma":									return 241;
				case "Zvezdin stadion":									return 242;
			}

			return 0;
		}
	}
}
